'use strict';
// ── KPI ───────────────────────────────────────────────────────
async function renderKPI(){const main=document.getElementById('mainContent');main.innerHTML=`<div class="page-title"><span>📈 KPI & Penilaian</span><button class="btn btn-primary btn-sm" onclick="modalKPI()">+ Tambah</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Karyawan</th><th>Periode</th><th>Skor</th><th>Grade</th><th>Penilai</th></tr></thead><tbody id="tblKPI"></tbody></table></div></div>`;const snap=await db.collection('hrd_kpi').get();let h='';if(snap.empty)h='<tr><td colspan="5" class="text-center">Belum ada</td></tr>';else snap.forEach(d=>{const p=d.data();const grade=p.skor>=90?'A':p.skor>=80?'B':p.skor>=70?'C':p.skor>=60?'D':'E';h+=`<tr><td class="fw-700">${escHtml(p.nama)}</td><td>${escHtml(p.periode)}</td><td><span class="badge badge-${p.skor>=80?'success':p.skor>=60?'warning':'danger'}">${p.skor}/100</span></td><td class="fw-700">${grade}</td><td>${escHtml(p.penilai||'-')}</td></tr>`;});document.getElementById('tblKPI').innerHTML=h;}
function modalKPI(){openModal(`<div class="modal-title">Tambah Penilaian KPI</div><div class="grid-2"><div class="form-group"><label>Karyawan</label><input class="form-control" id="kpiNama"></div><div class="form-group"><label>Periode</label><input class="form-control" id="kpiPeriode" value="${monthStr()}"></div></div><div class="grid-2"><div class="form-group"><label>Produktivitas (0-100)</label><input class="form-control" type="number" id="kpiProd" value="80"></div><div class="form-group"><label>Kualitas (0-100)</label><input class="form-control" type="number" id="kpiQual" value="80"></div></div><div class="grid-2"><div class="form-group"><label>Kedisiplinan (0-100)</label><input class="form-control" type="number" id="kpiDisc" value="80"></div><div class="form-group"><label>Kerjasama (0-100)</label><input class="form-control" type="number" id="kpiTeam" value="80"></div></div><div class="form-group"><label>Catatan</label><textarea class="form-control" id="kpiNote"></textarea></div><button class="btn btn-primary" onclick="simpanKPI()">Simpan</button>`);}
async function simpanKPI(){const prod=Number(document.getElementById('kpiProd').value)||0,qual=Number(document.getElementById('kpiQual').value)||0,disc=Number(document.getElementById('kpiDisc').value)||0,team=Number(document.getElementById('kpiTeam').value)||0;const skor=Math.round((prod+qual+disc+team)/4);await db.collection('hrd_kpi').add({nama:document.getElementById('kpiNama').value,periode:document.getElementById('kpiPeriode').value,produktivitas:prod,kualitas:qual,kedisiplinan:disc,kerjasama:team,skor,catatan:document.getElementById('kpiNote').value,penilai:currentUser.nama,createdAt:new Date().toISOString()});closeModalDirect();toast('KPI disimpan','success');renderKPI();}

// ── PELATIHAN ─────────────────────────────────────────────────
async function renderPelatihan(){const main=document.getElementById('mainContent');main.innerHTML=`<div class="page-title"><span>🎓 Pelatihan & Sertifikasi</span><button class="btn btn-primary btn-sm" onclick="modalPelatihan()">+ Tambah</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Judul</th><th>Jenis</th><th>Tanggal</th><th>Peserta</th><th>Status</th><th>Aksi</th></tr></thead><tbody id="tblPelatihan"></tbody></table></div></div>`;const snap=await db.collection('hrd_pelatihan').get();let h='';if(snap.empty)h='<tr><td colspan="6" class="text-center">Belum ada</td></tr>';else snap.forEach(d=>{const p=d.data();h+=`<tr><td class="fw-700">${escHtml(p.judul)}</td><td>${escHtml(p.jenis)}</td><td>${formatDate(p.tanggal)}</td><td>${(p.peserta||[]).length}</td><td><span class="badge badge-${p.status==='selesai'?'success':'info'}">${p.status||'terjadwal'}</span></td><td><button class="btn btn-xs btn-info" onclick="modalPelatihan('${d.id}')">✏️</button></td></tr>`;});document.getElementById('tblPelatihan').innerHTML=h;}
function modalPelatihan(id){if(id)db.collection('hrd_pelatihan').doc(id).get().then(d=>showPelForm(id,d.data()||{}));else showPelForm(null,{});}
function showPelForm(id,p){openModal(`<div class="modal-title">${id?'Edit':'Tambah'} Pelatihan</div><div class="form-group"><label>Judul</label><input class="form-control" id="pelJudul" value="${escHtml(p.judul||'')}"></div><div class="grid-2"><div class="form-group"><label>Jenis</label><select class="form-control" id="pelJenis"><option value="internal" ${p.jenis==='internal'?'selected':''}>Internal</option><option value="eksternal" ${p.jenis==='eksternal'?'selected':''}>Eksternal</option><option value="sertifikasi" ${p.jenis==='sertifikasi'?'selected':''}>Sertifikasi</option></select></div><div class="form-group"><label>Tanggal</label><input class="form-control" type="date" id="pelTgl" value="${p.tanggal||''}"></div></div><div class="form-group"><label>Peserta (koma)</label><input class="form-control" id="pelPeserta" value="${(p.peserta||[]).join(', ')}"></div><div class="form-group"><label>Status</label><select class="form-control" id="pelStatus"><option value="terjadwal" ${p.status==='terjadwal'?'selected':''}>Terjadwal</option><option value="selesai" ${p.status==='selesai'?'selected':''}>Selesai</option></select></div><button class="btn btn-primary" onclick="simpanPelatihan('${id||''}')">Simpan</button>`);}
async function simpanPelatihan(id){const data={judul:document.getElementById('pelJudul').value,jenis:document.getElementById('pelJenis').value,tanggal:document.getElementById('pelTgl').value,peserta:document.getElementById('pelPeserta').value.split(',').map(s=>s.trim()).filter(Boolean),status:document.getElementById('pelStatus').value,updatedAt:new Date().toISOString()};if(!data.judul)return toast('Judul wajib','warning');if(id)await db.collection('hrd_pelatihan').doc(id).update(data);else await db.collection('hrd_pelatihan').add({...data,createdAt:new Date().toISOString()});closeModalDirect();toast('Disimpan','success');renderPelatihan();}

// ── KONTRAK ───────────────────────────────────────────────────
async function renderKontrak(){const main=document.getElementById('mainContent');main.innerHTML=`<div class="page-title"><span>📄 Kontrak & Perjanjian</span><button class="btn btn-primary btn-sm" onclick="modalKontrak()">+ Tambah</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Judul</th><th>Pihak</th><th>Mulai</th><th>Berakhir</th><th>Status</th><th>Aksi</th></tr></thead><tbody id="tblKontrak"></tbody></table></div></div>`;const snap=await db.collection('hrd_kontrak').get();const today=todayStr();let h='';if(snap.empty)h='<tr><td colspan="6" class="text-center">Belum ada</td></tr>';else snap.forEach(d=>{const p=d.data();const expired=p.berakhir<today;h+=`<tr><td class="fw-700">${escHtml(p.judul)}</td><td>${escHtml(p.pihak||'-')}</td><td>${formatDate(p.mulai)}</td><td>${formatDate(p.berakhir)}</td><td><span class="badge badge-${expired?'danger':'success'}">${expired?'Expired':'Aktif'}</span></td><td><button class="btn btn-xs btn-info" onclick="modalKontrak('${d.id}')">✏️</button> <button class="btn btn-xs btn-danger" onclick="hapusDoc('hrd_kontrak','${d.id}','kontrak')">🗑️</button></td></tr>`;});document.getElementById('tblKontrak').innerHTML=h;}
function modalKontrak(id){if(id)db.collection('hrd_kontrak').doc(id).get().then(d=>showKontrakForm(id,d.data()||{}));else showKontrakForm(null,{});}
function showKontrakForm(id,p){openModal(`<div class="modal-title">${id?'Edit':'Tambah'} Kontrak</div><div class="form-group"><label>Judul</label><input class="form-control" id="ktJudul" value="${escHtml(p.judul||'')}"></div><div class="grid-2"><div class="form-group"><label>Pihak</label><input class="form-control" id="ktPihak" value="${escHtml(p.pihak||'')}"></div><div class="form-group"><label>Jenis</label><select class="form-control" id="ktJenis"><option value="kerja" ${p.jenis==='kerja'?'selected':''}>Kontrak Kerja</option><option value="vendor" ${p.jenis==='vendor'?'selected':''}>Vendor</option><option value="nda" ${p.jenis==='nda'?'selected':''}>NDA</option></select></div></div><div class="grid-2"><div class="form-group"><label>Mulai</label><input class="form-control" type="date" id="ktMulai" value="${p.mulai||''}"></div><div class="form-group"><label>Berakhir</label><input class="form-control" type="date" id="ktAkhir" value="${p.berakhir||''}"></div></div><button class="btn btn-primary" onclick="simpanKontrak('${id||''}')">Simpan</button>`);}
async function simpanKontrak(id){const data={judul:document.getElementById('ktJudul').value,pihak:document.getElementById('ktPihak').value,jenis:document.getElementById('ktJenis').value,mulai:document.getElementById('ktMulai').value,berakhir:document.getElementById('ktAkhir').value,updatedAt:new Date().toISOString()};if(!data.judul)return toast('Judul wajib','warning');if(id)await db.collection('hrd_kontrak').doc(id).update(data);else await db.collection('hrd_kontrak').add({...data,createdAt:new Date().toISOString()});closeModalDirect();toast('Disimpan','success');renderKontrak();}

// ── ASSET ─────────────────────────────────────────────────────
async function renderAsset(){const main=document.getElementById('mainContent');main.innerHTML=`<div class="page-title"><span>💻 Asset Management</span><button class="btn btn-primary btn-sm" onclick="modalAsset()">+ Tambah</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Nama</th><th>Kategori</th><th>Pengguna</th><th>Kondisi</th><th>Aksi</th></tr></thead><tbody id="tblAsset"></tbody></table></div></div>`;const snap=await db.collection('hrd_asset').get();let h='';if(snap.empty)h='<tr><td colspan="6" class="text-center">Belum ada</td></tr>';else snap.forEach(d=>{const p=d.data();h+=`<tr><td>${escHtml(p.kode||'-')}</td><td class="fw-700">${escHtml(p.nama)}</td><td>${escHtml(p.kategori||'-')}</td><td>${escHtml(p.pengguna||'-')}</td><td><span class="badge badge-${p.kondisi==='baik'?'success':p.kondisi==='rusak'?'danger':'warning'}">${p.kondisi||'baik'}</span></td><td><button class="btn btn-xs btn-info" onclick="modalAsset('${d.id}')">✏️</button> <button class="btn btn-xs btn-danger" onclick="hapusDoc('hrd_asset','${d.id}','asset')">🗑️</button></td></tr>`;});document.getElementById('tblAsset').innerHTML=h;}
function modalAsset(id){if(id)db.collection('hrd_asset').doc(id).get().then(d=>showAssetForm(id,d.data()||{}));else showAssetForm(null,{});}
function showAssetForm(id,p){openModal(`<div class="modal-title">${id?'Edit':'Tambah'} Asset</div><div class="grid-2"><div class="form-group"><label>Kode</label><input class="form-control" id="asKode" value="${escHtml(p.kode||'AST-'+Date.now().toString().slice(-6))}"></div><div class="form-group"><label>Nama</label><input class="form-control" id="asNama" value="${escHtml(p.nama||'')}"></div></div><div class="grid-2"><div class="form-group"><label>Kategori</label><select class="form-control" id="asKat"><option value="elektronik" ${p.kategori==='elektronik'?'selected':''}>Elektronik</option><option value="furniture" ${p.kategori==='furniture'?'selected':''}>Furniture</option><option value="kendaraan" ${p.kategori==='kendaraan'?'selected':''}>Kendaraan</option></select></div><div class="form-group"><label>Kondisi</label><select class="form-control" id="asKondisi"><option value="baik" ${p.kondisi==='baik'?'selected':''}>Baik</option><option value="perlu_perbaikan" ${p.kondisi==='perlu_perbaikan'?'selected':''}>Perlu Perbaikan</option><option value="rusak" ${p.kondisi==='rusak'?'selected':''}>Rusak</option></select></div></div><div class="form-group"><label>Pengguna</label><input class="form-control" id="asPengguna" value="${escHtml(p.pengguna||'')}"></div><button class="btn btn-primary" onclick="simpanAsset('${id||''}')">Simpan</button>`);}
async function simpanAsset(id){const data={kode:document.getElementById('asKode').value,nama:document.getElementById('asNama').value,kategori:document.getElementById('asKat').value,kondisi:document.getElementById('asKondisi').value,pengguna:document.getElementById('asPengguna').value,updatedAt:new Date().toISOString()};if(!data.nama)return toast('Nama wajib','warning');if(id)await db.collection('hrd_asset').doc(id).update(data);else await db.collection('hrd_asset').add({...data,createdAt:new Date().toISOString()});closeModalDirect();toast('Disimpan','success');renderAsset();}

// ══════════════════════════════════════════════════════════════
